name: Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  node: ${{ vars.NODE_VERSION }}

jobs:

  one:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub env
        env:
          GITHUB_CONTEXT:  $GITHUB_ENV
        run: echo "$GITHUB_CONTEXT"
